### ISSUE TITLE
[Request] English Support

### ISSUE THREAD

**Issue by hikettei** [WSOFT-Project/lantana#58]
# 概要

Hello. I'm building documentation using your Lantana. Does this theme support English? When I open my documentation in the browser, some parts remain in Japanese:

![image](https://github.com/user-attachments/assets/894e2b59-c684-459c-bb1a-14b73581e1a5)

I'd like to ask if there’s a way to switch it to English, or if English support might be added.

(Here's my [mkdocs.yml](https://github.com/hikettei/Caten/blob/main/mkdocs.yml) `language` is set to en)

**Comment by taiseiue** [comment]
Thank you so much for using this project! I'm really sorry, but I don't have English (or multi-language) support yet. I know how important this is, so I'm going to make it a top priority and add it to the next release (which might be lantana-2.11).

**Comment by hikettei** [comment]
ありがとうございます！楽しみに待ってます！

**Comment by taiseiue** [comment]
今ほど[lantana==2.11.1](https://pypi.org/project/lantana/2.11.1/)をリリースしました〜
`mkdocs.yml`に以下のように設定いただければ、英語での使用が可能です。

```yml
theme: 
    name : "lantana"
    locale: en
```

---

他にお困りの点などがあれば、遠慮なくお尋ねください！
大丈夫そうであればこのIssueをクローズしていただいて構いません。

**Comment by taiseiue** [comment]
先ほど英語対応を[lantana==2.11.2](https://pypi.org/project/lantana/2.11.2/)として公開しました〜
このバージョン以降を使用していただいた上、`mkdocs.yml`に下記のように記載していただくと英語化ができます。

```yml
theme: 
    name : lantana
    locale: en
```

---
他にも困っている場所やご要望などあれば遠慮なくご連絡ください！
英語対応について、大丈夫そうであればこのIssueをクローズしていただいて構いません。

**Comment by hikettei** [comment]
問題なく適用できました，迅速な対応ありがとうございます！はい，これからも何かありましたらよろしくお願いします mm
